### ISSUE TITLE
UI resources: refresh value frame with button-action

### ISSUE THREAD

**Issue by leopoldHatFertig** [PHOENIXCONTACT/MORYX-AbstractionLayer#107]
**Is your feature request related to a problem? Please describe.**
The UI for the Resources has a non-intuitive refreshing behaviour. The existing "Refresh"-button only refreshes the left frame for the resources-tree, but not the right frame with the instance values. So pressing the button still might show old values on the right frame.
The right frame only gets refreshed after selecting a different resource-instance in the resource-tree. So, to refresh the values of the resource you have currently selected, you need to select another resource and select your resource again. 
This is 
a) non-intuitive and 
b) tiring to use.
Also, there is no extra button with the functionality to refresh to right value-frame.

**Describe the solution you'd like**
- The existing "Refresh"-Button should refresh the right value-frame as well (at least as long as it is not in editing mode)

**Describe alternatives you've considered**
In my opinion, this would be sufficient to implement an intuitive behaviour a user would expect when hitting the "Refresh"-button.
An alternative could be to implement an aditional button within the right frame that exclusively refreshes that frame.
Since 
a) this would mean having two Refrehs Buttons on one page, and
 b)  might overload the page with action buttons, 
I would prefer the first approach to have only one button and expand its functionality.
Your opinons that this are appreciated.

**Additional context**
![moryx_ui_resource_refresh](https://user-images.githubusercontent.com/49842684/124391563-7bf7d280-dcf1-11eb-8952-3854ede0f8f2.png)

**Comment by slawor** [comment]
Thank you for your contribution. We will consider this issue as soon as possible.
