### ISSUE TITLE
Product AutoConfigurator creates config for read only properties

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-AbstractionLayer#166]
**Describe the bug**
The AutoConfigurator creates config for read only properties. From my point of view, the `get`-only properties should be ignored.

My product have the following properties

````cs
public double Length { get; set; }

public string LengthString => Length.ToString("F");

public double Height { get; set; }

public string HeightString => Height.ToString("F");
````

**To Reproduce**
The AutoConfigurator is creating the following config for me:

````json
{
    "$type": "Moryx.Products.Management.GenericTypeConfiguration, Moryx.Products.Management",
    "PluginName": "GenericTypeStrategy",
    "JsonColumn": "Text8",
    "PropertyConfigs": [
        {
        "PropertyName": "Length",
        "PluginName": "FloatColumnMapper",
        "Column": "Float1"
        },
        {
        "PropertyName": "LengthString",
        "PluginName": "TextColumnMapper",
        "Column": "Text1"
        },
        {
        "PropertyName": "Height",
        "PluginName": "FloatColumnMapper",
        "Column": "Float2"
        },
        {
        "PropertyName": "HeightString",
        "PluginName": "TextColumnMapper",
        "Column": "Text2"
        }
    ],
    "TargetType": "MyProductType"
},
````

@Toxantron I was already on the way to fix this problem but I am not sure which is the right way:

- Assign `NullPropertyMapper` (which would maybe work for the AutoConfigurator) but what would a developer or user of the product management do?
- Ignore `get`-only properties in all mappers

**Comment by Toxantron** [comment]
I would prefer the latter.  Read-only properties are mostly "helpers", there is no point in the storage to consider them and once we move the endpoint out, the entire product management could ignore them.

> Ignore get-only properties in all mappers
