### ISSUE TITLE
Change product and resource service to WebHTTP and JSON

### ISSUE THREAD

**Issue by Toxantron** [PHOENIXCONTACT/MORYX-AbstractionLayer#26]
**Is your feature request related to a problem? Please describe.**
Our current WCF SOAP endpoints only work on .NET Framework and there is no acceptable solution to make them cross platform later.

**Describe the solution you'd like**
To prepare cross platform usage we must replace SOAP with standard URL and JSON web service before releasing the AL

**Describe alternatives you've considered**
Fully migrating to .NET Core is not an option because we still have projects and dependencies that only work with .NET Framework.

**Additional context**
Compare to Maintenance Endpoint Refactoring.

**Comment by Toxantron** [comment]
Since you also created the Maintenance Endpoints, are you interested on working on this @mmarkwort? I think you also had some ideas for the AL that als required JSON Endpoints.

**Comment by mmarkwort** [comment]
I'll can do that

**Comment by dbeuchler** [comment]
willl be done in #41
