### ISSUE TITLE
Support long running product importer

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-AbstractionLayer#31]
**Is your feature request related to a problem? Please describe.**
Currently the product importer requires an synchronous array of product types as return value. For single and simple importers this is enough but if importers gets more complex they must be asynchrounous. Sometimes we have importers which are running several minutes or hours.

**Describe the solution you'd like**
Provide asynchrounous api for importing products

````cs
Task<ProductType[]> Import(TParameters parameters);
````

**Comment by Toxantron** [comment]
This makes a lot of sense, especially when we consider that importers might call external services or read file streams

**Comment by dbeuchler** [comment]
done by #52
