### ISSUE TITLE
Exception on returning empty array while importing products

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-AbstractionLayer#32]
**Describe the bug**
Related to #31 - I use a workaround for executing my long running product importer and start the import within a new thread - so i wanted to return without any imported product:

**To Reproduce**
````cs
protected override IProductType[] Import(ClassicProductInstanceImportParameters parameters)
{
    return new IProductType[0];
}
````

**Expected behavior**
No error and no problem

**Additional context**
The web service always returns the element on array index 0 to the ui and this crashes. The UI does not use this information.

**Comment by Toxantron** [comment]
Huh, that must be legacy code from when the product importer could only import one product at a time and the UI would display the new item.

**Comment by dbeuchler** [comment]
done by #52
