### ISSUE TITLE
ProductUi and ResourceUi not working after uptdate to v.5.0.0-dev.120

### ISSUE THREAD

**Issue by H4llJ0rdan** [PHOENIXCONTACT/MORYX-AbstractionLayer#49]
**Describe the bug**
After an update of the abstraction layer to v.5.0.0-dev.120, the ProductUi and the ResourceUi are not working.
There is no exception thrown, the UIs simply do not load any content.
The wcf-viewer does not show a connection to products or resource service.

**To Reproduce**
1. Open a project, where the ProductUi and ResourceUi depend on wcf services.
2. Update the nuget packages of the AL to version v.5.0.0-dev.120.
3. Open the product or resource ui.
4. See that no products or resources are loaded.

**Comment by dbeuchler** [comment]
I currently dont know why exactly this is not working in you project but we definetly need log entries within the `WebHttpConnectorBase`

**Comment by Toxantron** [comment]
Did you remember to update client packages as well or just the server?

**Comment by H4llJ0rdan** [comment]
I could solve this issue by changing the configuration of the interaction hosts.

ProductManager -> InteractionHost (changable over the maintenance web ui)
- Endpoint: "products"
- Binding Type: "WebHttp"

ResourceManager -> InteractionHost (must be changed in database)
- {"HostConfig":{"Endpoint":"resources","BindingType":0,"MetadataEnabled":true}}

**Comment by Toxantron** [comment]
Thanks for the follow up and sorry for the inconvenience.
