### ISSUE TITLE
Replaceable product storage and database model

### ISSUE THREAD

**Issue by Toxantron** [PHOENIXCONTACT/MORYX-AbstractionLayer#6]
Right now the product model is part of the module and directly accessed by the service. Instead all calls to the model should be isolated in the storage to make it replaceable. Replacing it on the same data model does not make sense, as it already offers strategies for the different entity to business object conversions.

**Comment by 1nf0rmagician** [comment]
Instead we now provide replacable database providers underneath the product storage in MORYX 6

**Comment by dbeuchler** [comment]
This is for me not the right solution for it. I give you a real world example: We are using a product database with nearly 18.000 products which are read from an existing data source (json and / or mongodb). With replacing the database provider, I cannot replace the complete access to this data source. 

For this ticket, it would be nice if the source of the products can be changed and replaced. So make it possible to replace the storage of the products in the module would be nice. Instead, the only way to achieve this is to reimplement the product management by myself. 

There are also cases where I would say "Save recipes, workplans, instances and so on in the normal database but read the types from another source". Remember that we every time had cases where we read the types and import them. This would then not be required anymore.

**Comment by Toxantron** [comment]
> Save recipes, workplans, instances and so on in the normal database but read the types from another source

Especially in this case a replaceable storage would not work. 

We still offer the possibility, that you can read product types or part of them through the strategy from an external source. But the implementation of the product management including expression filtering on the facade etc is coupled to the storage and to some extent the data model. If we would make all of that replaceable, you are basically reimplementing the ProductManager anyway. If you want to partially replace it, you have the issues of all the foreign keys being broken. 

Making the storage replacible basically means making >80% of the module replaceable. It's less effort to reimplement the facade in a new module. You could even base it on our implementation legally. But from our perspective the benefits of not importing the types does not justify the effort and complexity required to achieve this.
