### ISSUE TITLE
Recipe TemplateId is not mapped by AutoMapper of Product Management

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-AbstractionLayer#99]
**Describe the bug**
The template id will not be automatically mapped by the auto mapper. For the `future` branch, the template is already an own column within the database (#92) .

**Expected behavior**
For AbstractionLayer 5.x the Id should be mapped automatically by the auto mapper

**Comment by Toxantron** [comment]
I agree and I tried the first time, but unless we want to add a hardcoded rule this would have required breaking a lot of the generic structure of the AutoMapper. However this will not be the last addition to products or recipes. Maybe we can base the AutoMapper on the AL 5.0 definitions within the interfaces and determine the diff to class implementation to find properties on the base classe initially not part of the datamodel.

**Comment by dbeuchler** [comment]
For me, a hard-coded rule would be ok, but the generic solution is also okay for me. In general, we are not planning to add a massive amount of properties in AL5 so a hardcoded solution is enough

**Comment by dbeuchler** [comment]
closed by #105
